INSERT INTO T_FINDIT_USUARIO (NM_USUARIO, NM_EMAIL, NM_SENHA) VALUES ('Vini', 'vini@gmail.com', '123')
INSERT INTO T_FINDIT_USUARIO (NM_USUARIO, NM_EMAIL, NM_SENHA) VALUES ('gojo', 'gojo@gmail.com', '123')
INSERT INTO T_FINDIT_USUARIO (NM_USUARIO, NM_EMAIL, NM_SENHA) VALUES ('fernando', 'fernando@gmail.com', '123')
INSERT INTO T_FINDIT_USUARIO (NM_USUARIO, NM_EMAIL, NM_SENHA) VALUES ('enrico', 'enrico@gmail.com', '123')
INSERT INTO T_FINDIT_USUARIO (NM_USUARIO, NM_EMAIL, NM_SENHA) VALUES ('pedro', 'pedro@gmail.com', '123')

INSERT INTO T_FINDIT_PREFERECIAS (NM_PREFERENCIA, TP_PREFERENCIA, DS_PREFERENCIA) VALUES ('teste', 'teste', 'teste')
INSERT INTO T_FINDIT_PREFERECIAS (NM_PREFERENCIA, TP_PREFERENCIA, DS_PREFERENCIA) VALUES ('teste', 'teste', 'teste')
INSERT INTO T_FINDIT_PREFERECIAS (NM_PREFERENCIA, TP_PREFERENCIA, DS_PREFERENCIA) VALUES ('teste', 'teste', 'teste')

INSERT INTO T_FINDIT_VIAGEM (DS_VIAGEM, DT_PARTIDA, DT_FIM) VALUES ('Londres', CURRENT_DATE, CURRENT_DATE)
INSERT INTO T_FINDIT_VIAGEM (DS_VIAGEM, DT_PARTIDA, DT_FIM) VALUES ('Japão', CURRENT_DATE, CURRENT_DATE)

INSERT INTO T_FINDIT_DESTINO (NM_DESTINO, DS_PONTOS_TURISTICOS, SG_PAIS) VALUES ('teste', 'teste', 'teste')
INSERT INTO T_FINDIT_DESTINO (NM_DESTINO, DS_PONTOS_TURISTICOS, SG_PAIS) VALUES ('teste', 'teste', 'teste')
